In [75]:
import numpy as np

In [76]:
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


In [77]:
b = np.array([[1.0,3.0,4.0],[4.0,5.0,3.0]], dtype= 'float32')
print(b)

[[1. 3. 4.]
 [4. 5. 3.]]


In [78]:
#Get Dimension
b.ndim
#a.ndim

2

In [79]:
#Get Shape
#a.shape
b.shape

(2, 3)

In [80]:
#Get Type
#a.dtype
b.dtype

dtype('float32')

In [81]:
#Get size
a.itemsize

2

In [82]:
#Get total size
a.nbytes

6

In [83]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [84]:
c.shape

(2, 7)

In [85]:
#Accessing
c[1,4]

12

In [86]:
c[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [87]:
c[:,4]

array([ 5, 12])

In [88]:
#[startindex:endindex:stepsize]
c[1,1:6:2]

array([ 9, 11, 13])

In [89]:
#change
#c[1,3] = 30
#c
c[:,2] = [34,56]
print(c)

[[ 1  2 34  4  5  6  7]
 [ 8  9 56 11 12 13 14]]


### 3D Dimension

In [90]:
d = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(d)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [91]:
d[:,1,:]

array([[3, 4],
       [8, 9]])

In [92]:
#replace
d[:,0,:] = [[2,7]]
d

array([[[2, 7],
        [3, 4]],

       [[2, 7],
        [8, 9]]])

### Initializing Different types of array

In [93]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.ones((2,3), dtype= 'int8')


array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [95]:
np.full((4,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [96]:
np.full_like(b.shape, 4)

array([4, 4])

In [97]:
# Random decimal no.
np.random.rand(4,5)

array([[0.09218808, 0.93990246, 0.89396245, 0.92855984, 0.10561737],
       [0.20782804, 0.53998642, 0.07529778, 0.02670584, 0.15404879],
       [0.69812463, 0.0538348 , 0.53304732, 0.00346457, 0.79615438],
       [0.94697484, 0.60325864, 0.33769645, 0.16249625, 0.2322898 ]])

In [98]:
#Random Integer Values 
np.random.randint(2,6, size=(3,3))

array([[2, 4, 5],
       [3, 5, 5],
       [4, 2, 5]])

In [99]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [101]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [102]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [103]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful When Copying arrays!!!

In [104]:
e = np.array([12,22,32])
g = e.copy()

g[0] = 100
g

#print(g)
#print(e)

array([100,  22,  32])

In [105]:
print(e)

[12 22 32]


## Mathematics

In [106]:
h = np.array([1,2,3,4])
print(a)

[1 2 3]


In [107]:
a + 2

array([3, 4, 5], dtype=int16)

In [108]:
a - 2

array([-1,  0,  1], dtype=int16)

In [109]:
a * 2

array([2, 4, 6], dtype=int16)

In [110]:
a / 2

array([0.5, 1. , 1.5])

In [111]:
b = np.array([1,0,1,0])
h + b

array([2, 2, 4, 4])

In [112]:
h ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [113]:
# Take the sin
np.sin(h)
#np.cos(h)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### For More (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## Linear Algebra

In [114]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [115]:
# Find the determinant
c = np.identity(4)
np.linalg.det(c)

1.0

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Determinant
#### Trace
#### Singular Vector decomposition
#### Eigenvalues
#### Matrix Norm
#### Inverse
#### Etc....

## Statistics

In [116]:
stats = np.array([[1,2,3],[5,6,7]])
stats

array([[1, 2, 3],
       [5, 6, 7]])

In [117]:
np.mean(stats)

4.0

In [118]:
np.min(stats)

1

In [119]:
np.median(stats)

4.0

In [120]:
np.max(stats, axis=1)

array([3, 7])

In [121]:
np.sum(stats, axis=0)

array([ 6,  8, 10])

## Reorganizing Arrays

In [122]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [123]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])  
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])  

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [124]:
# Horizontal stack
h1 = np.zeros([2,2])  
h2 = np.ones([2,4])

np.hstack([h2,h1,h2])

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

## Miscellaneous

#### Load Data From Files

In [125]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 123,  23,  45,  67,
        89,  67,  56,  45, 234,  45,  67,  56,   9,  98,  99,  87,  76,
        65,  54,  43,  32,  12,  13,  14,  15,  16,  17,  18,  19,  23,
        24,  25,  26,  26,  27,  28,  29,  32,  33,  34,  35,  36,  37,
        38,  39,  44, 454,  46,  47,  48,  45,  46,  45])

##### Boolean Masking and Advanced Indexing

In [126]:
filedata > 50

array([False, False, False, False, False, False, False, False, False,
        True, False, False,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False])

In [127]:
filedata[filedata >50]

array([123,  67,  89,  67,  56, 234,  67,  56,  98,  99,  87,  76,  65,
        54, 454])

In [128]:
l = np.array([1,3,4,5,6])
l[[1,2,4]]

array([3, 4, 6])

In [129]:
np.all(filedata > 50, axis=0)

False

In [131]:
  ((filedata > 50) & (filedata < 100))

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [132]:
  (~(filedata > 50) & (filedata < 100))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True])

## Thank You 